version: '3'

services:
  phpadmin:
    image: 'phpmyadmin/phpmyadmin:latest'
    environment:
      - PMA_HOST=mariadb
      - PMA_PORT=3306
      - PMA_USER=bn_opencart
    ports:
      - '8888:80'
    networks:
      - test_net

  mariadb:
    image: docker.io/bitnami/mariadb:11.2
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=bn_opencart
      - MARIADB_DATABASE=bitnami_opencart
    volumes:
      - 'mariadb_data:/bitnami/mariadb'
    ports:
      - '3306:3306'
    networks:
      - test_net

  opencart:
    image: docker.io/bitnami/opencart:4
    ports:
      - '8081:8080'
      - '443:8443'
    environment:
      - OPENCART_HOST=${LOCAL_IP}:8081
      - OPENCART_DATABASE_HOST=mariadb
      - OPENCART_DATABASE_PORT_NUMBER=3306
      - OPENCART_DATABASE_USER=bn_opencart
      - OPENCART_DATABASE_NAME=bitnami_opencart
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - 'opencart_data:/bitnami/opencart'
      - 'opencart_storage_data:/bitnami/opencart_storage/'
    depends_on:
      - mariadb
    networks:
      - test_net

  selenoid:
    image: "aerokube/selenoid"
    network_mode: bridge
    ports:
      - "4444:4444"
    volumes:
      - "/Users/sergeyfrolkin/.jenkins/workspace/homework/:/etc/selenoid/" # assumed current dir contains browsers.json
      - "/var/run/docker.sock:/var/run/docker.sock"

  selenoid-ui:
    image: "aerokube/selenoid-ui"
    network_mode: bridge
    depends_on:
      - selenoid
    links:
      - selenoid
    ports:
      - "8090:8080"
    command: [ "--selenoid-uri", "http://${LOCAL_IP}:4444" ]

  chrome124:
    image: selenoid/chrome:124.0
    depends_on:
      - selenoid
      - selenoid-ui

  chrome123:
    image: selenoid/chrome:123.0
    depends_on:
      - selenoid
      - selenoid-ui

  tests:
    image: tests_container:v1
    build:
      dockerfile: tests/Dockerfile
    depends_on:
      - opencart
      - selenoid
      - selenoid-ui
    command: ./wait-for-it.sh ${LOCAL_IP} 8081 -- pytest /tests -n 2 --browser chrome --bv "124.0" --vnc
    container_name: tests_container
    networks:
      - test_net
    volumes:
      - "/Users/sergeyfrolkin/.jenkins/workspace/homework/allure-results/:/allure-results/"
      - "/Users/sergeyfrolkin/.jenkins/workspace/homework/tests/logs/:/tests/logs/"

networks:
  test_net:

volumes:
  mariadb_data:
    driver: local
  opencart_data:
    driver: local
  opencart_storage_data:
    driver: local
